apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: frontend-config
spec:
  sslPolicy: gke-ingress-ssl-policy
  redirectToHttps:
    enabled: true

    # gcloud compute ssl-policies create gke-ingress-ssl-policy \
    # --profile MODERN \
    # --min-tls-version 1.2